language: php

php:
  - 5.6
  - 5.5

notifications:
  email:
    recipients:
      - tech@pmg.com
    on_success: change
    on_failure: always

before_install:
    - curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar -xz -C /tmp
    - cd /tmp/beanstalkd-1.10
    - make
    - ./beanstalkd &
    - cd $TRAVIS_BUILD_DIR

install: composer install --prefer-source

script: make test
