language: php

php:
  - "8.0"

env:
  matrix:
    - COMPOSER_FLAGS=""
    - COMPOSER_FLAGS="--prefer-lowest"

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email: false

before_install:
    - curl -L https://github.com/beanstalkd/beanstalkd/archive/refs/tags/v1.12.tar.gz | tar -xz -C /tmp
    - cd /tmp/beanstalkd-1.12
    - make
    - ./beanstalkd &
    - cd $TRAVIS_BUILD_DIR

install:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script: make test
