list_tubes:
  path:     /api/queue/tubes
  defaults: { _controller: AppBundle:Queue:listTubes }
  methods:  [GET]

get_tube:
  path:     /api/queue/{tube}
  defaults: { _controller: AppBundle:Queue:getInfo }
  methods:  [GET]

list_all_info:
  path:     /api/queue
  defaults: { _controller: AppBundle:Queue:listInfo }
  methods:  [GET]
