list_tubes:
  path:     /queue/tubes
  defaults: { _controller: PmgPheanstalkBundle:Queue:listTubes }
  methods:  [GET]

get_tube:
  path:     /queue/{tube}
  defaults: { _controller: PmgPheanstalkBundle:Queue:getInfo }
  methods:  [GET]

list_all_info:
  path:     /queue
  defaults: { _controller: PmgPheanstalkBundle:Queue:listInfo }
  methods:  [GET]
