name: test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: test
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version: ["8.2", "8.3"]
        composer-command:
          - composer update --prefer-lowest --prefer-dist --prefer-stable
          - composer install

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: start beanstalkd
        run: docker-compose up -d

      - name: PHP
        uses: ./.github/actions/setup-php
        with:
          php-version: "${{ matrix.php-version }}"
          composer-command: ${{ matrix.composer-command }}

      - name: tests
        run: ./vendor/bin/phpunit
